secrets:
  common:
    dbHost: "elib-rds.ccf0agc26wl5.us-east-1.rds.amazonaws.com"
    dbUser: "admin"
    dbPassword: "anhquan1234"

  auth:
    jwtKid: "e42b298d5d27d533a8a1d8f7bf7a828f"
    jwtPrivatePem: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDE97EJ+yuzHA8i
      YTp3U95wLZ0OOqEIsbMSnequo/LvKH5e6iytqyG/PYB8J8koc/AP9mkTPPJqt8Wf
      Ybr4vovr3k+lFe9Qu9L1Xvvgxq2PEY5Ar+dAGXo+8nihmdgZKHan198MM96rwwK0
      kozjR3TmJNPI23H5GtQ5hpuN9Ua3NdROXlWC9t9HLFdmE7/PnpJnpp134/0T9/8Y
      oUPOleORp3t1gyrnaoDsr2XBMDmGoyeMhTr5tvi0u6Z4D5c/gGmdbEenv2Uj7DNN
      fBtCzNdHYFr0fgE9Ec5UM22k5fVvA1icYpiLgJzTv7czu0qFfdes39mtqB+W3EwD
      lEm/nvjTAgMBAAECggEADX3N0ZoztxP/8WHpiEzlWpe1P0lCyH6rfmX0sjumoz0J
      0uSFZOvo5tmGmHp9K9ktI1rEfb3Z+PdXgQBHt0wN930FxZAIEWacH5R++jmBn+Aa
      91FVLK3SEse2/ZK1G5wK7Jo7u/E9mlRENiwnnFXDqxPwsbxeRSrSSJJwyzt2uYvG
      mIE9w9I7QIQxx5DS2F5+WOlMCojcqHdRKMpowUtT7DhCaSo+DkU0U2zjk0b/zORf
      c7ev00ESvpjgAcIrYE3YtDY+mYILTlLHVsTVlARUvxJQA6dCo1bpsAiKs88UcBb3
      btNRvjVtfBBPZJI6eh8gqq6GUISDXHvRf3hYhlw+eQKBgQDi5WgtexkoU8cmBknW
      iyMxaG+50d2VXgG5NxU7CRn8mbbz9AaySKuJY3F2eoUKlaIZr05/hbnJiFi2b23C
      oD2Oa3c4plzeUVhkzdd6UXXk7Gf+RTgdbaxLHwwrbwmV2JGv1S+JZMVczmEGRfYu
      zYJs4dcoAN6hDtj0v8rfyGuu5wKBgQDeO4TwmH1yXDAVKKo8sFwzWejglB+oXLbS
      ZIIxvBHRNaJAI6MuSHKD2Mi90rKJG/5arRLxze2sMr0CBL6CEz5276LkP5DmuSNP
      H4pgOV8dgLgzSLhxbyiMOJ52fD8ErMaonnA31uHRlg/3Tve/JE0mmR+QBp3RR4+T
      Ei5asuTFNQKBgCNUr5UtbuxtpzwPjJ3gypkd9w/LUyK4IbKSlja8IxTHZsqz+/r0
      /+kD2B4n0+GjDTvMpX+L9jMgjRfTYBcHVq5/o2/pz9o6dnYz61K7roz4FvVsF+HV
      OxfzfLSitK5lq8Hig2V0kJrz8/3DFSOSkrWbsSIkiIYxxqzN1KxmDAaPAoGBAJPM
      PdPNdtDR4uCPlPibyhYU275QhOVyE9zFH5l4HNlotCm4CdTENfTd/lPQhxCM35Lq
      vEi4zjLR48Yt5Y2YwthS86Cdbf8kbgk3Ts5EGbADZX4mBRTb+rmXBjyC0V6Ike6e
      wL9CWBkNljzB9h7XQ8BB4i3lWJxQ3XnQg6eqhl9pAoGBAIb0axGTOzqzNtYFpyIl
      XE5FdRPJfFXem0DZM/KqOPnqP131RSNwKLceakEB4lwDoZXKklosnfdLXR0XRAGV
      gcoEYN2JjYn3vAvGgCZ9QXpoZxMBxMKHevN5eaCYm7p5Q60zDRiPchIIMy+Fdird
      nd4dLQo6kLVL6rC9EsVfSHAh
      -----END PRIVATE KEY-----
    jwtPublicPem: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxPexCfsrsxwPImE6d1Pe
      cC2dDjqhCLGzEp3qrqPy7yh+Xuosrashvz2AfCfJKHPwD/ZpEzzyarfFn2G6+L6L
      695PpRXvULvS9V774MatjxGOQK/nQBl6PvJ4oZnYGSh2p9ffDDPeq8MCtJKM40d0
      5iTTyNtx+RrUOYabjfVGtzXUTl5VgvbfRyxXZhO/z56SZ6add+P9E/f/GKFDzpXj
      kad7dYMq52qA7K9lwTA5hqMnjIU6+bb4tLumeA+XP4BpnWxHp79lI+wzTXwbQszX
      R2Ba9H4BPRHOVDNtpOX1bwNYnGKYi4Cc07+3M7tKhX3XrN/ZragfltxMA5RJv574
      0wIDAQAB
      -----END PUBLIC KEY-----
