{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "elib-chart.fullname" . }}-ingress
  namespace: {{ include "elib-chart.namespace" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if .Values.ingress.tls.enabled }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.tls.certificateArn | quote }}
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host | quote }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "elib-chart.componentFullname" (dict "root" . "name" "web") }}
                port:
                  number: {{ .Values.web.service.port }}
{{- end }}