{{- if and .Values.auth.enabled .Values.auth.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elib-chart.serviceAccountName" (dict "root" . "name" "auth" "serviceAccount" .Values.auth.serviceAccount) }}
  namespace: {{ include "elib-chart.namespace" . }}
---
{{- end }}

{{- if and .Values.catalog.enabled .Values.catalog.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elib-chart.serviceAccountName" (dict "root" . "name" "catalog" "serviceAccount" .Values.catalog.serviceAccount) }}
  namespace: {{ include "elib-chart.namespace" . }}
---
{{- end }}

{{- if and .Values.borrow.enabled .Values.borrow.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elib-chart.serviceAccountName" (dict "root" . "name" "borrow" "serviceAccount" .Values.borrow.serviceAccount) }}
  namespace: {{ include "elib-chart.namespace" . }}
{{- end }}