{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elib-chart.componentFullname" (dict "root" . "name" "web") }}
  namespace: {{ include "elib-chart.namespace" . }}
  labels:
    {{- include "elib-chart.componentLabels" (dict "root" . "name" "web") | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "elib-chart.componentSelectorLabels" (dict "root" . "name" "web") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "elib-chart.componentSelectorLabels" (dict "root" . "name" "web") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "elib-chart.serviceAccountName" (dict "root" . "name" "web" "serviceAccount" .Values.web.serviceAccount) }}
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.containerPort }}
              name: http
          readinessProbe:
            httpGet:
              path: {{ .Values.web.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.web.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.web.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.web.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.probes.liveness.periodSeconds }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
{{- end }}