{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "elib-chart.componentFullname" (dict "root" . "name" "web") }}
  namespace: {{ include "elib-chart.namespace" . }}
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "elib-chart.componentSelectorLabels" (dict "root" . "name" "web") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
{{- end }}